#!/usr/bin/env bash
# =============================================================================
# build.sh — FlowGate air-gapped deployment builder
#
# Run this on an internet-connected machine that has Docker and Go installed.
# It builds the proxy image, pulls all external images, saves them as gzipped
# tarballs, and packages everything into the deployment/ folder ready to be
# copied to an air-gapped host.
#
# Usage:
#   bash build.sh                    # auto-version from git SHA
#   VERSION=1.2.0 bash build.sh      # explicit version tag
#   MINIO_VERSION=RELEASE.2025-01-01T00-00-00Z bash build.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${SCRIPT_DIR}/deployment"
IMAGES_DIR="${DEPLOY_DIR}/images"

# ── Versions ──────────────────────────────────────────────────────────────────
VERSION="${VERSION:-$(git -C "${SCRIPT_DIR}" rev-parse --short HEAD 2>/dev/null || echo 'dev')}"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
MINIO_VERSION="${MINIO_VERSION:-release.2026-01-02t17-54-56z}"

PROXY_IMAGE="flowgate"
PROXY_TAG="${PROXY_IMAGE}:${VERSION}"
PROXY_TAG_LATEST="${PROXY_IMAGE}:latest"
MINIO_IMAGE="ghcr.io/iamzoy/minio:${MINIO_VERSION}"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
info "Pre-flight checks"

command -v docker &>/dev/null  || die "docker not found — install Docker first"
docker info &>/dev/null        || die "Docker daemon not running"

success "Docker OK"

# ── Prepare output directories ────────────────────────────────────────────────
info "Preparing deployment/ directory"
mkdir -p "${IMAGES_DIR}"
success "deployment/images/ ready"

# ── Build the proxy Docker image ──────────────────────────────────────────────
info "Building Docker image ${PROXY_TAG}"

docker build \
    --build-arg VERSION="${VERSION}" \
    --build-arg BUILD_DATE="${BUILD_DATE}" \
    --tag "${PROXY_TAG}" \
    --tag "${PROXY_TAG_LATEST}" \
    "${SCRIPT_DIR}"

success "Built ${PROXY_TAG}"

# ── Pull external images ──────────────────────────────────────────────────────
info "Pulling ${MINIO_IMAGE}"
docker pull "${MINIO_IMAGE}"
success "Pulled ${MINIO_IMAGE}"

# ── Save images as gzipped tarballs ──────────────────────────────────────────
info "Saving images to ${IMAGES_DIR}/"

info "  Saving ${PROXY_TAG} → flowgate.tar.gz"
docker save "${PROXY_TAG}" | gzip > "${IMAGES_DIR}/flowgate.tar.gz"
success "  Saved flowgate.tar.gz ($(du -sh "${IMAGES_DIR}/flowgate.tar.gz" | cut -f1))"

info "  Saving ${MINIO_IMAGE} → minio.tar.gz"
docker save "${MINIO_IMAGE}" | gzip > "${IMAGES_DIR}/minio.tar.gz"
success "  Saved minio.tar.gz ($(du -sh "${IMAGES_DIR}/minio.tar.gz" | cut -f1))"

# ── Generate deployment files ─────────────────────────────────────────────────
info "Generating deployment files"

# Production config.yaml with TLS pre-configured
cat > "${DEPLOY_DIR}/config.yaml" <<'CONFIGEOF'
server:
  host: "0.0.0.0"
  port: 8443
  tls_cert: "/certs/flowgate.crt"
  tls_key: "/certs/flowgate.key"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  path: "./flowgate.db"
  max_open_connections: 5
  max_idle_connections: 2

transfer:
  worker_pool_size: 10
  queue_capacity: 1000
  # retry_attempts: 0    # default 0 (disabled). Set >0 to enable retries.
  # retry_backoff: "0s"  # base backoff between retries (exponential with jitter)

logging:
  level: "info"
  format: "json"

security:
  secret_key: "${SECRET_KEY}"

dashboard:
  enabled: true
  auth_enabled: false
  username: "admin"
  password: "${DASH_PASSWORD}"
CONFIGEOF
success "  config.yaml written"

# Production docker-compose (uses pre-loaded images, no build: directive)
cat > "${DEPLOY_DIR}/docker-compose.yml" <<EOF
# Generated by build.sh on ${BUILD_DATE}
# Do NOT edit the image: tags — they must match what was loaded by deploy.sh

services:
  flowgate:
    image: ${PROXY_TAG}
    restart: unless-stopped
    ports:
      - "\${FLOWGATE_PORT:-443}:8443"
    volumes:
      - ./config.yaml:/etc/flowgate/config.yaml:ro
      - ./certs:/certs:ro
      - flowgate-data:/data
    environment:
      SECRET_KEY: \${SECRET_KEY:?SECRET_KEY must be set in .env}
      LOG_LEVEL: \${LOG_LEVEL:-info}
    command: ["--config", "/etc/flowgate/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-qO-", "https://localhost:8443/health"]
      interval: 15s
      timeout:  5s
      retries:  3
    networks:
      - flowgate-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  flowgate-data:

networks:
  flowgate-net:
    driver: bridge
EOF
success "  docker-compose.yml written"

# .env with auto-generated placeholder (deploy.sh fills it)
cat > "${DEPLOY_DIR}/.env" <<'EOF'
# FlowGate Environment Variables
# SECRET_KEY is auto-generated by deploy.sh on first run if still a placeholder.

# REQUIRED — AES-GCM master key for encrypting MinIO credentials in SQLite.
SECRET_KEY=PLACEHOLDER_WILL_BE_AUTO_GENERATED

# Host port for HTTPS (maps to container port 8443)
FLOWGATE_PORT=443

# Logging level override
LOG_LEVEL=info
EOF
success "  .env written"

# ── Write deploy.sh for the target host ───────────────────────────────────────
cat > "${DEPLOY_DIR}/deploy.sh" <<'DEPLOYEOF'
#!/usr/bin/env bash
# =============================================================================
# deploy.sh — run this on the target host
#
# Prerequisites:
#   - Docker Engine + docker compose plugin (v2)
#   - openssl (for auto-generating SECRET_KEY and TLS certificates)
#
# Steps:
#   1. Copy the entire deployment/ folder to the host
#   2. bash deploy.sh    (auto-generates certs + SECRET_KEY)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="${SCRIPT_DIR}/images"
CERTS_DIR="${SCRIPT_DIR}/certs"
ENV_FILE="${SCRIPT_DIR}/.env"

# ── Pre-flight ────────────────────────────────────────────────────────────────
command -v docker   &>/dev/null || die "docker not found — install Docker first"
docker info         &>/dev/null || die "Docker daemon not running"
command -v openssl  &>/dev/null || die "openssl not found — required for certificate and key generation"

[[ -f "${SCRIPT_DIR}/config.yaml" ]]        || die "config.yaml not found"
[[ -f "${ENV_FILE}" ]]                       || die ".env not found"
[[ -f "${IMAGES_DIR}/flowgate.tar.gz" ]]     || die "images/flowgate.tar.gz not found"

# ── Auto-generate SECRET_KEY if placeholder ───────────────────────────────────
if grep -q 'PLACEHOLDER_WILL_BE_AUTO_GENERATED' "${ENV_FILE}"; then
    info "Generating SECRET_KEY"
    NEW_KEY="$(openssl rand -hex 32)"
    [[ -n "${NEW_KEY}" ]] || die "Failed to generate SECRET_KEY"
    sed -i.bak "s/PLACEHOLDER_WILL_BE_AUTO_GENERATED/${NEW_KEY}/" "${ENV_FILE}"
    rm -f "${ENV_FILE}.bak"
    success "SECRET_KEY generated and saved to .env"
    warn "IMPORTANT: Back up your .env file — losing SECRET_KEY makes encrypted data unrecoverable"
fi

# ── Generate self-signed TLS certificate if not present ───────────────────────
if [[ ! -f "${CERTS_DIR}/flowgate.crt" ]] || [[ ! -f "${CERTS_DIR}/flowgate.key" ]]; then
    info "Generating self-signed TLS certificate"
    mkdir -p "${CERTS_DIR}"

    # Detect primary IP address (Linux: hostname -I, macOS: ipconfig)
    LOCAL_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || ipconfig getifaddr en0 2>/dev/null || echo '127.0.0.1')"

    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "${CERTS_DIR}/flowgate.key" \
        -out "${CERTS_DIR}/flowgate.crt" \
        -days 3650 \
        -subj "/CN=flowgate" \
        -addext "subjectAltName=DNS:localhost,DNS:flowgate,IP:127.0.0.1,IP:${LOCAL_IP}" \
        2>/dev/null

    chmod 600 "${CERTS_DIR}/flowgate.key"
    chmod 644 "${CERTS_DIR}/flowgate.crt"
    success "TLS certificate generated (valid for 10 years)"
    success "  SANs: localhost, flowgate, 127.0.0.1, ${LOCAL_IP}"
else
    success "TLS certificates already present in certs/"
fi

# ── Load images ───────────────────────────────────────────────────────────────
info "Loading Docker images (this may take a minute)"

info "  Loading flowgate"
docker load < "${IMAGES_DIR}/flowgate.tar.gz"
success "  flowgate loaded"

if [[ -f "${IMAGES_DIR}/minio.tar.gz" ]]; then
    info "  Loading minio"
    docker load < "${IMAGES_DIR}/minio.tar.gz"
    success "  minio loaded"
fi

# ── Start services ────────────────────────────────────────────────────────────
info "Starting services with docker compose"
cd "${SCRIPT_DIR}"
docker compose --env-file .env up -d --remove-orphans

# ── Wait for health ───────────────────────────────────────────────────────────
info "Waiting for flowgate to become healthy"
ATTEMPTS=0
MAX=24
until docker compose ps flowgate | grep -q "healthy" || [[ ${ATTEMPTS} -ge ${MAX} ]]; do
    sleep 5
    ATTEMPTS=$((ATTEMPTS + 1))
    echo "  ... waiting (${ATTEMPTS}/${MAX})"
done

if [[ ${ATTEMPTS} -ge ${MAX} ]]; then
    echo ""
    die "flowgate did not become healthy in time — check: docker compose logs flowgate"
fi

success "flowgate is healthy"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Deployment complete.${RESET}"
echo ""
PORT="$(grep -v '^#' .env | grep FLOWGATE_PORT | cut -d= -f2 || echo 443)"
PORT="${PORT:-443}"
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || ipconfig getifaddr en0 2>/dev/null || echo 'localhost')"

echo "  Dashboard : https://${HOST_IP}:${PORT}"
echo "  Health    : https://${HOST_IP}:${PORT}/health"
echo "  Logs      : docker compose logs -f flowgate"
echo ""
DEPLOYEOF

chmod +x "${DEPLOY_DIR}/deploy.sh"
success "  deploy.sh written (executable)"

# ── Write manifest ────────────────────────────────────────────────────────────
cat > "${DEPLOY_DIR}/manifest.txt" <<EOF
FlowGate Deployment Manifest
================================
Built by   : $(whoami)@$(hostname)
Build date : ${BUILD_DATE}
Proxy image: ${PROXY_TAG}
MinIO image: ${MINIO_IMAGE}

Images
------
flowgate.tar.gz  $(sha256sum "${IMAGES_DIR}/flowgate.tar.gz" | awk '{print $1}')
minio.tar.gz     $(sha256sum "${IMAGES_DIR}/minio.tar.gz"    | awk '{print $1}')
EOF
success "  manifest.txt written"

# ── Cleanup legacy files ─────────────────────────────────────────────────────
rm -f "${DEPLOY_DIR}/.env.example" "${DEPLOY_DIR}/config.example.yaml"
rm -f "${IMAGES_DIR}/diode-proxy.tar.gz"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Build complete.${RESET}"
echo ""
echo "  Output folder : ${DEPLOY_DIR}"
echo "  Proxy image   : ${PROXY_TAG}"
echo "  MinIO image   : ${MINIO_IMAGE}"
echo "  Build date    : ${BUILD_DATE}"
echo ""
echo "  Total size    : $(du -sh "${DEPLOY_DIR}" | cut -f1)"
echo ""
echo "Next steps:"
echo "  1. tar -czf flowgate-deployment.tar.gz deployment/"
echo "  2. Copy the tarball to the target host"
echo "  3. On the host: tar -xzf flowgate-deployment.tar.gz"
echo "  4. On the host: cd deployment && bash deploy.sh"
echo ""
