#!/usr/bin/env bash
# =============================================================================
# build.sh — FlowGate air-gapped deployment builder
#
# Run this on an internet-connected machine that has Docker and Go installed.
# It builds the proxy image, pulls all external images, saves them as gzipped
# tarballs, and packages everything into the deployment/ folder ready to be
# copied to an air-gapped host.
#
# Usage:
#   bash build.sh                    # auto-version from git SHA
#   VERSION=1.2.0 bash build.sh      # explicit version tag
#   MINIO_VERSION=RELEASE.2025-01-01T00-00-00Z bash build.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${SCRIPT_DIR}/deployment"
IMAGES_DIR="${DEPLOY_DIR}/images"

# ── Versions ──────────────────────────────────────────────────────────────────
VERSION="${VERSION:-$(git -C "${SCRIPT_DIR}" rev-parse --short HEAD 2>/dev/null || echo 'dev')}"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
MINIO_VERSION="${MINIO_VERSION:-release.2026-01-02t17-54-56z}"

PROXY_IMAGE="flowgate"
PROXY_TAG="${PROXY_IMAGE}:${VERSION}"
PROXY_TAG_LATEST="${PROXY_IMAGE}:latest"
MINIO_IMAGE="ghcr.io/iamzoy/minio:${MINIO_VERSION}"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
info "Pre-flight checks"

command -v docker &>/dev/null  || die "docker not found — install Docker first"
docker info &>/dev/null        || die "Docker daemon not running"

success "Docker OK"

# ── Prepare output directories ────────────────────────────────────────────────
info "Preparing deployment/ directory"
mkdir -p "${IMAGES_DIR}"
success "deployment/images/ ready"

# ── Build the proxy Docker image ──────────────────────────────────────────────
info "Building Docker image ${PROXY_TAG}"

docker build \
    --build-arg VERSION="${VERSION}" \
    --build-arg BUILD_DATE="${BUILD_DATE}" \
    --tag "${PROXY_TAG}" \
    --tag "${PROXY_TAG_LATEST}" \
    "${SCRIPT_DIR}"

success "Built ${PROXY_TAG}"

# ── Pull external images ──────────────────────────────────────────────────────
info "Pulling ${MINIO_IMAGE}"
docker pull "${MINIO_IMAGE}"
success "Pulled ${MINIO_IMAGE}"

# ── Save images as gzipped tarballs ──────────────────────────────────────────
info "Saving images to ${IMAGES_DIR}/"

info "  Saving ${PROXY_TAG} → flowgate.tar.gz"
docker save "${PROXY_TAG}" | gzip > "${IMAGES_DIR}/flowgate.tar.gz"
success "  Saved flowgate.tar.gz ($(du -sh "${IMAGES_DIR}/flowgate.tar.gz" | cut -f1))"

info "  Saving ${MINIO_IMAGE} → minio.tar.gz"
docker save "${MINIO_IMAGE}" | gzip > "${IMAGES_DIR}/minio.tar.gz"
success "  Saved minio.tar.gz ($(du -sh "${IMAGES_DIR}/minio.tar.gz" | cut -f1))"

# ── Copy static deployment files ─────────────────────────────────────────────
info "Copying deployment files"

cp "${SCRIPT_DIR}/config.example.yaml"   "${DEPLOY_DIR}/config.example.yaml"

# Production docker-compose (uses pre-loaded images, no build: directive)
cat > "${DEPLOY_DIR}/docker-compose.yml" <<EOF
# Generated by build.sh on ${BUILD_DATE}
# Do NOT edit the image: tags — they must match what was loaded by deploy.sh

services:
  flowgate:
    image: ${PROXY_TAG}
    restart: unless-stopped
    ports:
      - "\${FLOWGATE_PORT:-8080}:8080"
    volumes:
      - ./config.yaml:/config.yaml:ro
      - flowgate-data:/data
    environment:
      FLOWGATE_DATABASE_PATH: /data/flowgate.db
      FLOWGATE_SECURITY_SECRET_KEY: \${SECRET_KEY:?SECRET_KEY must be set in .env}
      FLOWGATE_LOGGING_LEVEL: \${LOG_LEVEL:-info}
    command: ["--config", "/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 15s
      timeout:  5s
      retries:  3
    networks:
      - flowgate-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  flowgate-data:

networks:
  flowgate-net:
    driver: bridge
EOF
success "  docker-compose.yml written"

# ── Write .env template ───────────────────────────────────────────────────────
cat > "${DEPLOY_DIR}/.env.example" <<'EOF'
# Copy this to .env and fill in the values before running deploy.sh

# REQUIRED — used to derive the AES-GCM key that encrypts MinIO credentials in SQLite.
# Generate with: openssl rand -hex 32
SECRET_KEY=change-me-to-a-random-32-byte-hex-string

# OPTIONAL
FLOWGATE_PORT=8080
LOG_LEVEL=info
EOF
success "  .env.example written"

# ── Write deploy.sh for the air-gapped host ───────────────────────────────────
cat > "${DEPLOY_DIR}/deploy.sh" <<'DEPLOYEOF'
#!/usr/bin/env bash
# =============================================================================
# deploy.sh — run this on the air-gapped host
#
# Prerequisites on the target host:
#   - Docker Engine installed (no internet needed after this)
#   - docker compose plugin (v2)
#
# Steps:
#   1. Copy the entire deployment/ folder to the host
#   2. cp config.example.yaml config.yaml && edit config.yaml
#   3. cp .env.example .env              && edit .env (set SECRET_KEY)
#   4. bash deploy.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="${SCRIPT_DIR}/images"

# ── Pre-flight ────────────────────────────────────────────────────────────────
command -v docker &>/dev/null || die "docker not found"
docker info &>/dev/null       || die "Docker daemon not running"

[[ -f "${SCRIPT_DIR}/config.yaml" ]]  || die "config.yaml not found — copy config.example.yaml and edit it"
[[ -f "${SCRIPT_DIR}/.env" ]]         || die ".env not found — copy .env.example and set SECRET_KEY"
[[ -f "${IMAGES_DIR}/flowgate.tar.gz" ]] || die "images/flowgate.tar.gz not found"
[[ -f "${IMAGES_DIR}/minio.tar.gz" ]]        || die "images/minio.tar.gz not found"

# ── Load images ───────────────────────────────────────────────────────────────
info "Loading Docker images (this may take a minute)"

info "  Loading flowgate"
docker load < "${IMAGES_DIR}/flowgate.tar.gz"
success "  flowgate loaded"

info "  Loading minio"
docker load < "${IMAGES_DIR}/minio.tar.gz"
success "  minio loaded"

# ── Start services ────────────────────────────────────────────────────────────
info "Starting services with docker compose"
cd "${SCRIPT_DIR}"
docker compose --env-file .env up -d --remove-orphans

# ── Wait for health ───────────────────────────────────────────────────────────
info "Waiting for flowgate to become healthy"
ATTEMPTS=0
MAX=24
until docker compose ps flowgate | grep -q "healthy" || [[ ${ATTEMPTS} -ge ${MAX} ]]; do
    sleep 5
    ATTEMPTS=$((ATTEMPTS + 1))
    echo "  ... waiting (${ATTEMPTS}/${MAX})"
done

if [[ ${ATTEMPTS} -ge ${MAX} ]]; then
    echo ""
    die "flowgate did not become healthy in time — check: docker compose logs flowgate"
fi

success "flowgate is healthy"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Deployment complete.${RESET}"
echo ""
PORT="$(grep FLOWGATE_PORT .env 2>/dev/null | cut -d= -f2 || echo 8080)"
echo "  Dashboard : http://$(hostname -I | awk '{print $1}'):${PORT:-8080}"
echo "  Health    : http://$(hostname -I | awk '{print $1}'):${PORT:-8080}/health"
echo "  Logs      : docker compose logs -f flowgate"
echo ""
DEPLOYEOF

chmod +x "${DEPLOY_DIR}/deploy.sh"
success "  deploy.sh written (executable)"

# ── Write manifest ────────────────────────────────────────────────────────────
cat > "${DEPLOY_DIR}/manifest.txt" <<EOF
FlowGate Deployment Manifest
================================
Built by   : $(whoami)@$(hostname)
Build date : ${BUILD_DATE}
Proxy image: ${PROXY_TAG}
MinIO image: ${MINIO_IMAGE}

Images
------
flowgate.tar.gz  $(sha256sum "${IMAGES_DIR}/flowgate.tar.gz" | awk '{print $1}')
minio.tar.gz        $(sha256sum "${IMAGES_DIR}/minio.tar.gz"       | awk '{print $1}')
EOF
success "  manifest.txt written"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Build complete.${RESET}"
echo ""
echo "  Output folder : ${DEPLOY_DIR}"
echo "  Proxy image   : ${PROXY_TAG}"
echo "  MinIO image   : ${MINIO_IMAGE}"
echo "  Build date    : ${BUILD_DATE}"
echo ""
echo "  Total size    : $(du -sh "${DEPLOY_DIR}" | cut -f1)"
echo ""
echo "Next steps:"
echo "  1. tar -czf flowgate-deployment.tar.gz deployment/"
echo "  2. Copy the tarball to the air-gapped host"
echo "  3. On the host: tar -xzf flowgate-deployment.tar.gz"
echo "  4. On the host: cd deployment && bash deploy.sh"
echo ""
