#!/usr/bin/env bash
# =============================================================================
# deploy.sh — run this on the target host
#
# Prerequisites:
#   - Docker Engine + docker compose plugin (v2)
#   - openssl (for auto-generating SECRET_KEY and TLS certificates)
#
# Steps:
#   1. Copy the entire deployment/ folder to the host
#   2. bash deploy.sh    (auto-generates certs + SECRET_KEY)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}==>${RESET} ${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}✔${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET}  $*"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGES_DIR="${SCRIPT_DIR}/images"
CERTS_DIR="${SCRIPT_DIR}/certs"
ENV_FILE="${SCRIPT_DIR}/.env"

# ── Pre-flight ────────────────────────────────────────────────────────────────
command -v docker   &>/dev/null || die "docker not found — install Docker first"
docker info         &>/dev/null || die "Docker daemon not running"
command -v openssl  &>/dev/null || die "openssl not found — required for certificate and key generation"

[[ -f "${SCRIPT_DIR}/config.yaml" ]]        || die "config.yaml not found"
[[ -f "${ENV_FILE}" ]]                       || die ".env not found"
[[ -f "${IMAGES_DIR}/flowgate.tar.gz" ]]     || die "images/flowgate.tar.gz not found"

# ── Auto-generate SECRET_KEY if placeholder ───────────────────────────────────
if grep -q 'PLACEHOLDER_WILL_BE_AUTO_GENERATED' "${ENV_FILE}"; then
    info "Generating SECRET_KEY"
    NEW_KEY="$(openssl rand -hex 32)"
    [[ -n "${NEW_KEY}" ]] || die "Failed to generate SECRET_KEY"
    sed -i.bak "s/PLACEHOLDER_WILL_BE_AUTO_GENERATED/${NEW_KEY}/" "${ENV_FILE}"
    rm -f "${ENV_FILE}.bak"
    success "SECRET_KEY generated and saved to .env"
    warn "IMPORTANT: Back up your .env file — losing SECRET_KEY makes encrypted data unrecoverable"
fi

# ── Auto-generate dashboard admin password if placeholder/missing ─────────────
if ! grep -q '^DASH_PASSWORD=' "${ENV_FILE}"; then
    {
        echo ""
        echo "# Dashboard admin password (auto-generated by deploy.sh if still the placeholder)"
        echo "DASH_PASSWORD=CHANGE_ME_DASH_PASSWORD"
    } >> "${ENV_FILE}"
fi
if grep -q 'CHANGE_ME_DASH_PASSWORD' "${ENV_FILE}"; then
    info "Generating dashboard admin password"
    NEW_PW="$(openssl rand -base64 12 | tr -d '/+=')"
    [[ -n "${NEW_PW}" ]] || die "Failed to generate dashboard password"
    sed -i.bak "s/CHANGE_ME_DASH_PASSWORD/${NEW_PW}/" "${ENV_FILE}"
    rm -f "${ENV_FILE}.bak"
    success "Dashboard password generated and saved to .env (DASH_PASSWORD)"
fi

# ── Generate self-signed TLS certificate if not present ───────────────────────
if [[ ! -f "${CERTS_DIR}/flowgate.crt" ]] || [[ ! -f "${CERTS_DIR}/flowgate.key" ]]; then
    info "Generating self-signed TLS certificate"
    mkdir -p "${CERTS_DIR}"

    # Detect primary IP address (Linux: hostname -I, macOS: ipconfig)
    LOCAL_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || ipconfig getifaddr en0 2>/dev/null || echo '127.0.0.1')"

    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "${CERTS_DIR}/flowgate.key" \
        -out "${CERTS_DIR}/flowgate.crt" \
        -days 3650 \
        -subj "/CN=flowgate" \
        -addext "subjectAltName=DNS:localhost,DNS:flowgate,IP:127.0.0.1,IP:${LOCAL_IP}" \
        2>/dev/null

    chmod 600 "${CERTS_DIR}/flowgate.key"
    chmod 644 "${CERTS_DIR}/flowgate.crt"
    success "TLS certificate generated (valid for 10 years)"
    success "  SANs: localhost, flowgate, 127.0.0.1, ${LOCAL_IP}"
else
    success "TLS certificates already present in certs/"
fi

# ── Load images ───────────────────────────────────────────────────────────────
info "Loading Docker images (this may take a minute)"

info "  Loading flowgate"
docker load < "${IMAGES_DIR}/flowgate.tar.gz"
success "  flowgate loaded"

if [[ -f "${IMAGES_DIR}/minio.tar.gz" ]]; then
    info "  Loading minio"
    docker load < "${IMAGES_DIR}/minio.tar.gz"
    success "  minio loaded"
fi

# ── Start services ────────────────────────────────────────────────────────────
info "Starting services with docker compose"
cd "${SCRIPT_DIR}"
docker compose --env-file .env up -d --remove-orphans

# ── Wait for health ───────────────────────────────────────────────────────────
info "Waiting for flowgate to become healthy"
ATTEMPTS=0
MAX=24
until docker compose ps flowgate | grep -q "healthy" || [[ ${ATTEMPTS} -ge ${MAX} ]]; do
    sleep 5
    ATTEMPTS=$((ATTEMPTS + 1))
    echo "  ... waiting (${ATTEMPTS}/${MAX})"
done

if [[ ${ATTEMPTS} -ge ${MAX} ]]; then
    echo ""
    die "flowgate did not become healthy in time — check: docker compose logs flowgate"
fi

success "flowgate is healthy"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Deployment complete.${RESET}"
echo ""
PORT="$(grep -v '^#' .env | grep FLOWGATE_PORT | cut -d= -f2 || echo 443)"
PORT="${PORT:-443}"
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || ipconfig getifaddr en0 2>/dev/null || echo 'localhost')"

DASH_PW="$(grep '^DASH_PASSWORD=' .env | cut -d= -f2- || echo '')"

echo "  Dashboard : https://${HOST_IP}:${PORT}"
echo "  Login     : admin / ${DASH_PW}   (stored in .env as DASH_PASSWORD)"
echo "  Health    : https://${HOST_IP}:${PORT}/health"
echo "  Logs      : docker compose logs -f flowgate"
echo ""
